global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus self-monitoring metrics

  - job_name: 'flask_app'
    static_configs:
      - targets: ['localhost:8001']

  - job_name: 'node-exporter host'    #node exporter host node
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'node-exporter workers'   # node exporter for worker nodes
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.13.19:9100', '10.0.1.252:9100', '10.0.9.203:9100', '10.0.5.216:9100', '10.0.10.85:9100']
