# Use a minimal base image
FROM ubuntu:latest

# Set the environment variable to avoid tzdata interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary system dependencies
RUN apt-get update && apt-get install -y \
    wget \
    git \
    tar \
    bzip2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Miniconda and set up the environment
RUN mkdir -p ~/miniconda3 \
    && wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh \
    && /bin/bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 \
    && rm -rf ~/miniconda3/miniconda.sh \
    && ~/miniconda3/bin/conda init bash

# Set environment variables
ENV PATH /root/miniconda3/bin:$PATH

# Install awscli
RUN apt-get update && apt-get install -y awscli && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create a Conda environment with Python 3.8 and install packages
RUN conda create -n myenv python=3.8 -y && \
    echo "source activate myenv" > ~/.bashrc && \
    /bin/bash -c "source activate myenv && \
    conda install -c conda-forge -c bioconda hhsuite biopython numpy && \
    conda install -c anaconda pandas scipy && \
    conda install -c pytorch pytorch && \
    conda clean -t -i -p -y"

# Clone the s4pred repository and download the model weights
RUN git clone https://github.com/psipred/s4pred /s4pred \
    && cd /s4pred \
    && wget http://bioinfadmin.cs.ucl.ac.uk/downloads/s4pred/weights.tar.gz \
    && tar -xvzf weights.tar.gz \
    && rm weights.tar.gz

# Add your application's source code to the Docker image
COPY ./ /app
WORKDIR /app

# Make your scripts executable
RUN chmod +x ./pipeline_script.py ./results_parser.py

# Copy the entrypoint script and make it executable
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]

# Default argument
CMD ["input.fasta"]
