# Python base image
FROM python:3.8

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    tar \
    bzip2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Miniconda
ENV MINICONDA_VERSION 4.10.3
ENV CONDA_DIR /opt/conda
ENV PATH $CONDA_DIR/bin:$PATH

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py38_$MINICONDA_VERSION-Linux-x86_64.sh -O ~/miniconda.sh \
    && /bin/bash ~/miniconda.sh -b -p $CONDA_DIR \
    && rm ~/miniconda.sh \
    && conda clean -tipsy \
    && conda init bash \
    && . /root/.bashrc

# Install python packages
RUN conda install -c conda-forge -c bioconda hhsuite
RUN conda install -c conda-forge biopython
RUN conda install -c conda-forge numpy
RUN conda install -c anaconda pandas
RUN conda install -c anaconda scipy
RUN conda install -c pytorch pytorch

# Clone s4pred repo and download the model weights
RUN git clone https://github.com/psipred/s4pred /s4pred \
    && cd /s4pred \
    && wget http://bioinfadmin.cs.ucl.ac.uk/downloads/s4pred/weights.tar.gz \
    && tar -xvzf weights.tar.gz

# Add application's source code to the Docker image
COPY ./ /app
WORKDIR /app

# Make your scripts executable
RUN chmod +x ./pipeline_script.py ./results_parser.py

# Command to run your application
CMD ["python", "./pipeline_script.py", "input.fasta"]
