- name: change directory of docker to /mnt/data due to extra memory
  hosts: clients
  become: yes
  vars:
    new_docker_root: /mnt/data/docker

  tasks:
    - name: stop docker
      systemd:
        name: docker
        state: stopped

    - name: move docker directory
      command: mv /var/lib/docker "{{ new_docker_root }}"
      args:
        creates: "{{ new_docker_root }}"

    - name: create docker daemon config file
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "data-root": "{{ new_docker_root }}"
          }

    - name: restart docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes

    - name: verify new docker root dir
      command: docker info --format '{{"{{"}}.DockerRootDir{{"}}"}}'
      register: docker_info

    - name: assert docker root dir
      assert:
        that:
          - docker_info.stdout == new_docker_root

