---
- name: configure all nodes
  hosts: all
  become: yes
  tasks:
    - name: update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: install wget, git, curl, tar and bzip2 packages
      ansible.builtin.yum:
        name:
          - wget
          - git
          - curl
          - tar
          - bzip2
        state: latest

    - name: install firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: start and enable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: open ports  on nodes
      ansible.builtin.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items:
        - 22/tcp #ssh
        - 80/tcp #http
        - 9100/tcp # node exporter prometheus
        - 8001/tcp  # prometheus cleint for program
        - 8000/tcp # flask 
