---
- name: configure all nodes
  hosts: all
  become: yes
  tasks:
    - name: update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: install wget, git, and curl packages
      ansible.builtin.yum:
        name:
          - wget
          - git
          - curl
          - tar
          - bzip2
        state: latest

    - name: install firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: start and enable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: open port 22 (ssh) for ansible on nodes
      ansible.builtin.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items:
        - 22/tcp
