---
- name: Configure Kubernetes Cluster
  hosts: clients
  become: yes
  tasks:
    - name: Update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install wget, git, and curl packages
      ansible.builtin.yum:
        name:
          - wget
          - git
          - curl
        state: latest

    - name: Install firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Start and enable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Open necessary ports for client nodes for Kubernetes
      ansible.builtin.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items:
        - 10250/tcp # Kubelet API
        - 30000-32767/tcp # NodePort Services

    - name: Open port 22 (SSH) for Ansible on client nodes
      ansible.builtin.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items:
        - 22/tcp

    - name: Disable swap for Kuburnetes
      ansible.builtin.command:
        cmd: swapoff -a
      ignore_errors: true

    - name: Remove swap from /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^([^#].*?\s+swap\s+.*)$'
        line: '#\1'
        backrefs: yes
