---
- name: install docker on all aws nodes
  hosts: all
  become: yes
  tasks:
    - name: uninstall podman docker if its on the node
      yum:
        name: podman-docker
        state: absent

    - name: install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: add docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: install Docker
      yum:
        name: docker-ce
        state: present

    - name: start docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: create docker group
      group:
        name: docker
        state: present

    - name: giving ec2-user docker permissions
      user:
        name: ec2-user
        groups: docker
        append: yes
