- name: download pdb70 onto client nodes
  hosts: clients
  become: yes
  tasks:
    - name: download pdb70 file from internet
      get_url:
        url: "https://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb70_from_mmcif_latest.tar.gz"
        dest: "/mnt/data/pdb70_from_mmcif_latest.tar.gz"
        mode: 0750
        timeout: 3600
      register: download_result
      until: download_result is succeeded
      retries: 5 
      delay: 600  
      ignore_errors: False

    - name: create directory for pdb70
      ansible.builtin.file:
        path: "/mnt/data/pdb70"
        state: directory

    - block:
        - name: unzip file
          command: >
            tar -xzvf /mnt/data/pdb70_from_mmcif_latest.tar.gz -C /mnt/data/pdb70
          register: tar_result
          ignore_errors: yes

        - name: delete zip file
          file:
            path: "/mnt/data/pdb70_from_mmcif_latest.tar.gz"
            state: absent
          when: tar_result is defined and tar_result.rc == 0

      rescue:
        - name: unzip Failed
          debug:
            msg: "The unzipping process failed."

