---
- name: download pdb70 onto client nodes
  hosts: clients
  become: yes
  tasks:
    - name: download pdb70 file from internet
      command: >
        curl -o /mnt/data/pdb70_from_mmcif_latest.tar.gz "https://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/pdb70_from_mmcif_latest.tar.gz"
      args:
        creates: /mnt/data/pdb70_from_mmcif_latest.tar.gz

    - name: create directory for pdb70
      ansible.builtin.file:
        path: "/mnt/data/pdb70"
        state: directory

    - block:
        - name: unzip file
          command: >
            tar -xzvf /mnt/data/pdb70_from_mmcif_latest.tar.gz -C /mnt/data/pdb70
          register: tar_result
          ignore_errors: yes

        - name: delete zip file
          file:
            path: "/mnt/data/pdb70_from_mmcif_latest.tar.gz"
            state: absent
          when: tar_result is defined and tar_result.rc == 0

      rescue:
        - name: unzip Failed
          debug:
            msg: "The unzipping process failed."

