---
- name: Configure Host Node for Kuburnetes Cluster
  hosts: localhost
  become: yes
  tasks:
    - name: Update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install wget, git, and curl packages
      ansible.builtin.yum:
        name:
          - wget
          - git
          - curl
        state: latest

    - name: Install firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Start and enable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Open necessary ports for client nodes for Kubernetes
      ansible.builtin.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items:
        - 6443/tcp # Kubernetes API server
        - 2379-2380/tcp # etcd server client API
        - 10250/tcp # Kublet API
        - 10259/tcp # kublet-scheduler
        - 10257/tcp # kube-controller-manager
