- name: install conda packages & s4pred
  hosts: clients
  become: yes
  tasks:
    - name: activate conda environment and install numpy package
      shell: /bin/bash -c "source /mnt/data/miniconda3/bin/activate myenv && conda install -c anaconda numpy"
      environment:
        PATH: "{{ ansible_env.PATH }}:/mnt/data/miniconda3/bin"

    - name: install scipy package
      shell: /bin/bash -c "source /mnt/data/miniconda3/bin/activate myenv && conda install -c anaconda scipy"
      environment:
        PATH: "{{ ansible_env.PATH }}:/mnt/data/miniconda3/bin"

    - name: install pytorch package
      shell: /bin/bash -c "source /mnt/data/miniconda3/bin/activate myenv && conda install -c pytorch pytorch"
      environment:
        PATH: "{{ ansible_env.PATH }}:/mnt/data/miniconda3/bin"

    - name: install pandas package
      shell: /bin/bash -c "source /mnt/data/miniconda3/bin/activate myenv && conda install -c anaconda pandas"
      environment:
        PATH: "{{ ansible_env.PATH }}:/mnt/data/miniconda3/bin"

    - name: install hh-suite package
      shell: /bin/bash -c "source /mnt/data/miniconda3/bin/activate myenv && conda install -c conda-forge -c bioconda hhsuite"
      environment:
        PATH: "{{ ansible_env.PATH }}:/mnt/data/miniconda3/bin"

    - name: install biopython package
      shell: /bin/bash -c "source /mnt/data/miniconda3/bin/activate myenv && conda install -c conda-forge biopython"
      environment:
        PATH: "{{ ansible_env.PATH }}:/mnt/data/miniconda3/bin"

    - name: clone s4pred repository
      git:
        repo: https://github.com/psipred/s4pred
        dest: /s4pred
        force: yes

    - name: download model weights for s4pred
      shell: >
        cd /s4pred &&
        wget http://bioinfadmin.cs.ucl.ac.uk/downloads/s4pred/weights.tar.gz &&
        tar -xvzf weights.tar.gz &&
        rm weights.tar.gz

