- name: configure client nodes
  hosts: clients
  become: yes
  tasks:
    - name: run yum clean all
      ansible.builtin.command: sudo yum clean all

    - name: create miniconda directory
      ansible.builtin.file:
        path: /miniconda3
        state: directory

    - name: download miniconda installer
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /miniconda3/miniconda.sh

    - name: run miniconda installer
      shell: /bin/bash /miniconda3/miniconda.sh -b -u -p /miniconda3
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:/miniconda3/bin"

    - name: add miniconda to PATH in .bashrc
      lineinfile:
        path: /home/ec2-user/.bashrc
        line: 'export PATH="/miniconda3/bin:$PATH"'
        create: yes

    - name: initialize conda for bash
      shell: /miniconda3/bin/conda init bash
      environment:
        PATH: "{{ ansible_env.PATH }}:/miniconda3/bin"

    - name: create conda environment
      shell: >
        /bin/bash -c "conda create -n myenv python=3.8 -y"
      environment:
        PATH: "{{ ansible_env.PATH }}:/miniconda3/bin"

