---
- name: Configure Kubernetes Cluster
  hosts: all
  become: true
  tasks:
    - name: Disable Swap
      command: swapoff -a
      ignore_errors: true

    - name: Update SELinux configuration to set it to permissive
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'

    - name: Temporarily set SELinux to permissive
      command: setenforce 0

    - name: Install iproute-tc
      yum:
        name: iproute-tc
        state: present

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Load overlay module
      modprobe:
        name: overlay
        state: present

    - name: Enable IP Forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Enable iptables for bridges
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present
        reload: yes

    - name: Enable ip6tables for bridges
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: '1'
        state: present
        reload: yes


    - name: Add Kubernetes YUM repository
      yum_repository:
        name: kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: 
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Enable CRI-O repo
      shell: |
        export VERSION=1.28
        curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo
        curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/CentOS_8/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo

    - name: Install CRI-O
      yum:
        name: cri-o
        state: present

    - name: Enable and start CRI-O
      systemd:
        name: crio
        enabled: yes
        state: started

    - name: Install Kubeadm, Kubelet, and Kubectl
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubelet
        - kubectl
      notify:
        - restart kubelet

  handlers:
    - name: restart kubelet
      systemd:
        name: kubelet
        state: restarted

