---
- name: transfer and add new ssh public key to client nodes
  hosts: clients
  become: yes
  vars:
    new_public_key: ~/.ssh/id_cluster.pub
    ansible_user: ec2-user

  tasks:
    - name: ensure .ssh directory exists
      file:
        path: "~/.ssh"
        state: directory
        mode: '0700'

    - name: copy ssh public key to client nodes
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', new_public_key) }}"

